JWK_AddonIntegrationConfig {
 m_aItemAttributes {
  JWK_ItemAttributesConfigRule "{67113E2D125F5C5B}" {
   m_sTitle "Pistols"
   m_aPrefabs {
    "{29875F7D341C034F}Prefabs/Weapons/Handguns/CZ75/Handgun_CZ75.et"
   }
   m_ShopItemAttributes JWK_ShopItemAttributes "{67113E2D125F5C62}" {
    m_iMoneyPrice 25
   }
  }
  JWK_ItemAttributesConfigRule "{67113E2D125F5C64}" {
   m_sTitle "Pistol ammo"
   m_aPrefabs {
    "{FEE258E5316DD436}Prefabs/Weapons/Magazines/Magazine_9x19_CZ75_16rnd_Ball.et"
   }
   m_ShopItemAttributes JWK_ShopItemAttributes "{67113E2D125F5C67}" {
    m_iMoneyPrice 10
    m_iSuppliesPrice 2
   }
  }
 }
 m_aFactionAddons {
  JWK_ModFactionAddons "{67113E2D125FA73F}" {
   m_aTargetFactionRoles {
    PLAYER
   }
   m_aAddItems {
    "{29875F7D341C034F}Prefabs/Weapons/Handguns/CZ75/Handgun_CZ75.et"
    "{FEE258E5316DD436}Prefabs/Weapons/Magazines/Magazine_9x19_CZ75_16rnd_Ball.et"
   }
   m_LoadoutAddons JWK_LoadoutConfig "{67113E2D125FA73C}" {
    m_aWeaponSets {
     JWK_LoadoutWeaponsSetConfig "{67113E2D125FA722}" {
      m_sId "Cz75"
      m_aItems {
       JWK_LoadoutItemConfig "{67113E2D125FA723}" {
        m_iStoragePurpose PURPOSE_WEAPON_PROXY
        m_sPrefab "{29875F7D341C034F}Prefabs/Weapons/Handguns/CZ75/Handgun_CZ75.et"
       }
       JWK_LoadoutItemConfig "{67113E2D125FA720}" {
        m_sPrefab "{FEE258E5316DD436}Prefabs/Weapons/Magazines/Magazine_9x19_CZ75_16rnd_Ball.et"
        m_iAmount 2
       }
      }
     }
    }
   }
  }
 }
}