JWK_AddonIntegrationConfig {
 m_aItemAttributes {
  JWK_ItemAttributesConfigRule "{672AA7569872E103}" {
   m_sTitle "ChristmasHat"
   m_aPrefabs {
    "{0EF3C8357D0C18CD}Prefabs/Characters/HeadGear/Hat_Knitted_01/Hat_Christmas_Elf_MC.et"
    "{967F4CE563FD2853}Prefabs/Characters/HeadGear/Hat_Knitted_01/Hat_Christmas_MC.et"
   }
   m_ShopItemAttributes JWK_ShopItemAttributes "{672AA75688196E26}" {
    m_iMoneyPrice 30
    m_iSuppliesPrice 2
   }
  }
 }
 m_aFactionAddons {
  JWK_ModFactionAddons "{672AA756C60F6171}" {
   m_aTargetFactionRoles {
    PLAYER
    AMBIENT
   }
   m_aAddItems {
    "{0EF3C8357D0C18CD}Prefabs/Characters/HeadGear/Hat_Knitted_01/Hat_Christmas_Elf_MC.et"
    "{967F4CE563FD2853}Prefabs/Characters/HeadGear/Hat_Knitted_01/Hat_Christmas_MC.et"
   }
   m_LoadoutAddons JWK_LoadoutConfig "{672AA7553099D9FA}" {
    m_aSlots {
     JWK_LoadoutSlotConfig "{672AA7553135A726}" {
      m_iType HEADWEAR
      m_aChoices {
       "{0EF3C8357D0C18CD}Prefabs/Characters/HeadGear/Hat_Knitted_01/Hat_Christmas_Elf_MC.et"
       "{967F4CE563FD2853}Prefabs/Characters/HeadGear/Hat_Knitted_01/Hat_Christmas_MC.et"
      }
     }
    }
   }
  }
 }
}