JWK_AddonIntegrationConfig {
 m_aItemAttributes {
  JWK_ItemAttributesConfigRule "{67113E2F14AD88F6}" {
   m_sTitle "shoes"
   m_aPrefabs {
    "{342C8580EA528116}Prefabs/Characters/Footwear/JungleBoots_01/vans.et"
   }
   m_ShopItemAttributes JWK_ShopItemAttributes "{67113E2F14AD88EF}" {
    m_iMoneyPrice 25
   }
  }
 }
 m_aFactionAddons {
  JWK_ModFactionAddons "{67113E2F14AD88E4}" {
   m_aTargetFactionRoles {
    PLAYER
   }
   m_aAddItems {
    "{342C8580EA528116}Prefabs/Characters/Footwear/JungleBoots_01/vans.et"
   }
   m_LoadoutAddons JWK_LoadoutConfig "{67113E2F14AD88E5}" {
    m_aSlots {
     JWK_LoadoutSlotConfig "{67113E2FB9679C80}" {
      m_iType FOOTWEAR
      m_aChoices {
       "{342C8580EA528116}Prefabs/Characters/Footwear/JungleBoots_01/vans.et"
      }
     }
    }
   }
  }
 }
}