JWK_AddonIntegrationConfig {
 m_aItemAttributes {
  JWK_ItemAttributesConfigRule "{67113E2F8C02629B}" {
   m_sTitle "Tracksuit"
   m_aPrefabs {
    "{C41E26F1CF0135F5}Prefabs/Characters/Uniforms/Track_suit/TrackSuit_blue.et"
    "{3071DFCF7E4D2216}Prefabs/Characters/Uniforms/Track_suit_pants/Track_Suit_Pants.et"
   }
   m_ShopItemAttributes JWK_ShopItemAttributes "{67113E2F8C026292}" {
    m_iMoneyPrice 25
   }
  }
 }
 m_aFactionAddons {
  JWK_ModFactionAddons "{67113E2F8C026290}" {
   m_aTargetFactionRoles {
    AMBIENT
   }
   m_aAddItems {
    "{C41E26F1CF0135F5}Prefabs/Characters/Uniforms/Track_suit/TrackSuit_blue.et"
    "{3071DFCF7E4D2216}Prefabs/Characters/Uniforms/Track_suit_pants/Track_Suit_Pants.et"
   }
   m_LoadoutAddons JWK_LoadoutConfig "{67113E2F8C026296}" {
    m_aSlots {
     JWK_LoadoutSlotConfig "{67113E2F8C02C200}" {
      m_iType SHIRT
      m_aChoices {
       "{C41E26F1CF0135F5}Prefabs/Characters/Uniforms/Track_suit/TrackSuit_blue.et"
      }
     }
     JWK_LoadoutSlotConfig "{67114BB519EA036F}" {
      m_iType PANTS
      m_aChoices {
       "{3071DFCF7E4D2216}Prefabs/Characters/Uniforms/Track_suit_pants/Track_Suit_Pants.et"
      }
     }
    }
   }
  }
 }
}