JWK_AddonIntegrationConfig {
 m_aItemAttributes {
  JWK_ItemAttributesConfigRule "{67113E2951043D4C}" {
   m_sTitle "Rifles"
   m_aPrefabs {
    "{B452629074C5A1C5}Prefabs/Weapons/Rifles/SKS/SKS.et"
   }
   m_ShopItemAttributes JWK_ShopItemAttributes "{67113E2951043D45}" {
    m_iMoneyPrice 100
   }
  }
  JWK_ItemAttributesConfigRule "{67113E2951043D47}" {
   m_sTitle "Rifles ammo"
   m_aPrefabs {
    "{6ADC466FE3F54B64}Prefabs/Weapons/Magazines/SKS mag.et"
   }
   m_ShopItemAttributes JWK_ShopItemAttributes "{67113E2951043D78}" {
    m_iMoneyPrice 10
    m_iSuppliesPrice 2
   }
  }
  JWK_ItemAttributesConfigRule "{67113E29AF7CC847}" {
   m_sTitle "Machine Guns"
   m_aPrefabs {
    "{C18D7FFE8D840AF6}Prefabs/Weapons/Machineguns/DP-28/DP-28.et"
   }
   m_ShopItemAttributes JWK_ShopItemAttributes "{67113E29AF7CC8FA}" {
    m_iMoneyPrice 250
   }
  }
  JWK_ItemAttributesConfigRule "{67113E2984ED4EB5}" {
   m_sTitle "Machine gun ammo"
   m_aPrefabs {
    "{6EDDB5F04F641645}Prefabs/Weapons/Magazines/DP-28 disk.et"
   }
   m_ShopItemAttributes JWK_ShopItemAttributes "{67113E2984ED4950}" {
    m_iMoneyPrice 50
    m_iSuppliesPrice 5
   }
  }
 }
 m_aFactionAddons {
  JWK_ModFactionAddons "{67113E2951043D7B}" {
   m_aTargetFactionRoles {
    PLAYER
   }
   m_aAddItems {
    "{B452629074C5A1C5}Prefabs/Weapons/Rifles/SKS/SKS.et"
    "{6ADC466FE3F54B64}Prefabs/Weapons/Magazines/SKS mag.et"
    "{C18D7FFE8D840AF6}Prefabs/Weapons/Machineguns/DP-28/DP-28.et"
    "{6EDDB5F04F641645}Prefabs/Weapons/Magazines/DP-28 disk.et"
   }
   m_LoadoutAddons JWK_LoadoutConfig "{67113E2951043D7C}" {
    m_aWeaponSets {
     JWK_LoadoutWeaponsSetConfig "{67113E2951043D7D}" {
      m_sId "SKS"
      m_aItems {
       JWK_LoadoutItemConfig "{67113E2951043D7E}" {
        m_iStoragePurpose PURPOSE_WEAPON_PROXY
        m_sPrefab "{B452629074C5A1C5}Prefabs/Weapons/Rifles/SKS/SKS.et"
       }
       JWK_LoadoutItemConfig "{67113E2951043D7F}" {
        m_sPrefab "{6ADC466FE3F54B64}Prefabs/Weapons/Magazines/SKS mag.et"
        m_iAmount 10
       }
      }
     }
     JWK_LoadoutWeaponsSetConfig "{67113E2951043D71}" {
      m_sId "DP28"
      m_aItems {
       JWK_LoadoutItemConfig "{67113E2951043D72}" {
        m_iStoragePurpose PURPOSE_WEAPON_PROXY
        m_sPrefab "{C18D7FFE8D840AF6}Prefabs/Weapons/Machineguns/DP-28/DP-28.et"
       }
       JWK_LoadoutItemConfig "{67113E2951043D87}" {
        m_sPrefab "{6EDDB5F04F641645}Prefabs/Weapons/Magazines/DP-28 disk.et"
        m_iAmount 3
       }
      }
     }
    }
   }
  }
 }
}