JWK_AddonIntegrationConfig {
 m_aFactions {
  JWK_FactionConfig "{68E3739F10D9A542}" : "{D9AE686239216391}Configs/Factions/FF_UK_83.conf" {
  }
  JWK_FactionConfig "{68E3739F10F77054}" : "{5D2E7E0011E67120}Configs/Factions/FF_UK_89.conf" {
  }
 }
}